// Auto-generated by Supabase CLI
// Run: npm run db:generate to update

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      helpers: {
        Row: {
          id: string
          name: string
          telegram_user_id: number | null
          telegram_username: string | null
          is_admin: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          telegram_user_id?: number | null
          telegram_username?: string | null
          is_admin?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          telegram_user_id?: number | null
          telegram_username?: string | null
          is_admin?: boolean
          created_at?: string
        }
      }
      events: {
        Row: {
          id: string
          event_date: string
          title: string | null
          description: string | null
          imported_at: string
        }
        Insert: {
          id?: string
          event_date: string
          title?: string | null
          description?: string | null
          imported_at?: string
        }
        Update: {
          id?: string
          event_date?: string
          title?: string | null
          description?: string | null
          imported_at?: string
        }
      }
      assignments: {
        Row: {
          id: string
          event_id: string
          helper_id: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          helper_id: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          helper_id?: string
          created_at?: string
        }
      }
      event_status: {
        Row: {
          id: string
          event_id: string
          idea_ready: boolean
          food_communicated: boolean
          all_ready: boolean
          needs_help: boolean
          help_note: string | null
          kinderstunde_ready: boolean
          elternchat_communicated: boolean
          material_ready: boolean
          updated_at: string
        }
        Insert: {
          id?: string
          event_id: string
          idea_ready?: boolean
          food_communicated?: boolean
          all_ready?: boolean
          needs_help?: boolean
          help_note?: string | null
          kinderstunde_ready?: boolean
          elternchat_communicated?: boolean
          material_ready?: boolean
          updated_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          idea_ready?: boolean
          food_communicated?: boolean
          all_ready?: boolean
          needs_help?: boolean
          help_note?: string | null
          kinderstunde_ready?: boolean
          elternchat_communicated?: boolean
          material_ready?: boolean
          updated_at?: string
        }
      }
      reminder_log: {
        Row: {
          id: string
          event_id: string
          reminder_type: string
          sent_at: string
        }
        Insert: {
          id?: string
          event_id: string
          reminder_type: string
          sent_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          reminder_type?: string
          sent_at?: string
        }
      }
      ideas: {
        Row: {
          id: string
          event_id: string | null
          title: string
          description: string | null
          material: string | null
          was_used: boolean
          rating: string | null
          source: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id?: string | null
          title: string
          description?: string | null
          material?: string | null
          was_used?: boolean
          rating?: string | null
          source?: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string | null
          title?: string
          description?: string | null
          material?: string | null
          was_used?: boolean
          rating?: string | null
          source?: string
          created_at?: string
        }
      }
      children: {
        Row: {
          id: string
          name: string
          birthday: string | null
          notes: string | null
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          birthday?: string | null
          notes?: string | null
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          birthday?: string | null
          notes?: string | null
          active?: boolean
          created_at?: string
        }
      }
      settings: {
        Row: {
          id: string
          key: string
          value: string
          created_at: string
        }
        Insert: {
          id?: string
          key: string
          value: string
          created_at?: string
        }
        Update: {
          id?: string
          key?: string
          value?: string
          created_at?: string
        }
      }
      parents: {
        Row: {
          id: string
          name: string
          phone: string | null
          notes: string | null
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          phone?: string | null
          notes?: string | null
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          phone?: string | null
          notes?: string | null
          active?: boolean
          created_at?: string
        }
      }
      parent_duties: {
        Row: {
          id: string
          event_id: string
          parent_id: string
          created_at: string
        }
        Insert: {
          id?: string
          event_id: string
          parent_id: string
          created_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          parent_id?: string
          created_at?: string
        }
      }
      attendance_votes: {
        Row: {
          id: string
          event_id: string
          helper_id: string
          attending: boolean
          voted_at: string
        }
        Insert: {
          id?: string
          event_id: string
          helper_id: string
          attending: boolean
          voted_at?: string
        }
        Update: {
          id?: string
          event_id?: string
          helper_id?: string
          attending?: boolean
          voted_at?: string
        }
      }
    }
  }
}
